name: "Doc"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - run: ls -la ..
    - run: pip install Sphinx
    - run: mkdir -p build/html/_downloads
    - run: git rev-parse --short HEAD > scripts/compile_tools/version
    - run: git archive --format tar -o build/html/_downloads/Smilei.tar HEAD
    - run: tar rf build/html/_downloads/Smilei.tar scripts/compile_tools/version
    - run: gzip -f build/html/_downloads/Smilei.tar
    - run: make doc
