name: "Pull Request Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install git
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/Sphinx/"
